Add License: FPA General Code License
github/choosealicense.com pull request #1028
Opened 2022-09-02 19:37 UTC by William-McGonagle

2022-09-02 19:49 UTC, nschonni reviewed
Does this actually meet the criteria for inclusion https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

2022-09-02 19:49 UTC, nschonni commented on _licenses/fpa.txt
> +  Kubernetes: https://github.com/kubernetes/kubernetes/blob/master/LICENSE
These are all Apache 2.0 projects

2022-09-02 20:13 UTC, mlinksva commented
It does not meet the criteria for inclusion here as @nschonni points out.

Just a personal comment, the license seems very limited and or unclear. Is it `(personal OR educational) AND noncommercial-unless-substantial-changes`? What are "asset rips"?

2022-09-02 20:13 UTC, closed without merging

2022-09-03 15:31 UTC, William-McGonagle commented
Sorry- did not see the criteria about a 1,000 repository minimum. 

On another note @mlinksva, many open-source projects in areas like Game Development or Tooling want to provide their code while also not closing themselves off to revenue steam. This MIT-style license allows community contribution and uses in personal and educational settings while also not allowing corporations from taking the project and putting it onto stores themselves (a very common situation in open-source asset store projects). In other words, yes, it is `(personal OR educational) AND noncommerical-unless-substantial-changes`

2022-09-03 15:42 UTC, nschonni commented
Limiting a particular group is a violation of 5, so it actually wouldn't be considered an open source license https://opensource.org/osd
If you've also modified an existing license without using a lawyer to validate it, you may not be protecting yourself as the resulting changes @mlinksva found confusing might also be found unenforcable by a court

2022-09-03 16:58 UTC, William-McGonagle commented
@nschonni Yes- the license is legally binding as it was written by the legal professionals at the Fairfield Programming Association. As per not fitting into one organization's open-source definition, it is disappointing to hear about the lack of innovation that these rather closed organization have.

2022-09-03 20:04 UTC, mlinksva commented
@William-McGonagle, Nick probably meant (6) fields of endeavor rather than (5). (2) pertains to a program, not its license. The OSD does not mandate a license require source code, but a program without source code is not OSS per that definition even it is under an open license.

OSD aside (clearly you have no intention for the license to conform to it, which is of course totally up to you), I'm idly curious about whether I didn't misread and it is not actually `(personal OR educational) OR noncommerical-unless-substantial-changes`. It isn't super clear to me which it is, but if it were `AND` I'm not sure what the commercial term is supposed to permit -- a for-profit educational institution to substantially change and use? I guess from your described use case above, you want to allow any commercial use if substantially changed, such as making a new game and selling it on an app store? (Just a question of idle curiosity/learning.)

2022-09-03 20:09 UTC, mlinksva commented
ps not that you shouldn't make your own license, and indeed it's not quite the same, but noting it's a bit reminiscent of https://creativecommons.org/licenses/sampling/1.0/ and https://polyformproject.org/licenses/perimeter/1.0.0/

2022-09-04 00:19 UTC, William-McGonagle commented
@mlinksva - Yes! I'm delighted to hear about your curiosity, though it may be idly 😉. The license is designed so that users can support their projects commercially while still making their code and knowledge public to the open-source world. The reason that the 'educational context' is included is because the Fairfield Programming Association is a non-profit focused on education, so we wanted to let educational institutions (schools, universities, etc.) use the projects without running into problems with the 'commerical' section of the license. We told this to legal, and they gave us the 'educational context' wording. From what they explained, the legal precedent would allow 501(c)(3) educational institutions and for-profit educational institutions to "use, copy, modify, merge, publish, and/ or distribute copies" but not "sell and/ or distribute". 

One example of this is the MongoDB project, which has always been in collaboration with the community and switched its license to SSPL in 2018. They ran into a bit of a problem when it came to Amazon because Amazon simply forked the project for its own commercial gain. If say, MongoDB choose a semi-permissive, non-commercial license (I'm not really sure how else to word it) to start the project, they would have been able to keep this (FPA) license and pair it with a their own commercial license to sustain the project. Amazon would also be able to then fork the project and license it as its own if it significantly modified the code (Adding new features, making it lightweight, changing around the underlying systems, etc.) to make it its own type of MongoDB server. 

I know it doesn't fit the case of MongoDB quite perfectly, but this would be how licensing with something like this would work. Also if a school or person wanted to host their own MongoDB server, they would fully be able to– outside of a commercial context (financially gaining).

2023-04-20 01:46 UTC, Victorcorreiaaraujo requested changes
H