fix: #1236
github/choosealicense.com pull request #1237
Opened 2024-07-31 22:16 UTC by Malix-off

fix: #1236

2024-08-12 08:24 UTC, FisZika reviewed
420cdb27e8cbb41e786eb61b4fa21a4aa3bbfda8[](url)

2024-08-12 08:25 UTC, FisZika commented
0x2F99a7a81a3A446dB9fdfcaB10c47A406f874b50

2024-08-12 09:06 UTC, Malix-off commented
?

2025-09-29 13:28 UTC, Malix-Labs commented
@mlinksva could you kindly review this PR please? :smile:

2025-09-29 18:41 UTC, mlinksva requested changes

2025-09-29 18:41 UTC, mlinksva commented on _licenses/osl-3.0.txt
> +description: OSL 3.0 is a copyleft license that requires reciprocal licensing for derivative works. It also provides an express grant of patent rights from contributors to users, with a termination c
The existing text was probably meant to capture https://en.wikipedia.org/wiki/Open_Software_License#Linking_does_not_create_a_derivative_work (see references from there; the author's explanation is also linked in the `note:` field below).

Heres a rewrite that hopefully is more accuarate and is better matched with other descriptions on this site:

```suggestion
description: Permissions of this copyleft license are conditioned on distributing source code of licensed works and modifications under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. Using the work or modifications to provide services to external users is treated as distribution and also requires making source code available. Works that merely link to a licensed work are considered collective works and are not subject to the license's reciprocity requirements.
```

2025-09-29 19:04 UTC, mlinksva commented on _licenses/osl-3.0.txt
> +description: Permissions of this copyleft license are conditioned on distributing source code of licensed works and modifications under the same license. Copyright and license notices must be preserv
I'm afraid Copilot's review does not quite make sense so ignoring.

2025-09-29 19:06 UTC, mlinksva approved these changes

2025-09-29 19:29 UTC, merged