i18n using opensource.guide solution
github/choosealicense.com pull request #586
Opened 2018-04-27 02:23 UTC by matbrgz

Hello,

Close issue #68 

Acording to https://github.com/github/opensource.guide/pull/295 Guthub Pages does not support jekyll plugins. So I search at opensource.guide and try to do same.

- [X] Structure for localizing strings (_data/locale/zz.yml)
- [X] Update all strings in the markup
- [ ] Figure out structure for translating the guides themselves
- [ ] Tests for missing and unused localization strings
- [ ] Add locale switcher on the site
- [ ] Docs/process for translating the twitter cards
- [X] Complete one translation to make sure the infrastructure is sufficient
- [ ]  Document the translation process in CONTRIBUTING.md

2018-04-27 02:24 UTC, MatheusRV commented
`Your site is having problems building: There was a YAML syntax error on line 27 column 3 in _data/locale/en-US.yml: could not find expected ':' while scanning a simple key. For more information, see https://help.github.com/articles/page-build-failed-invalid-yaml-in-data-file/.`

`  licenses: The content of this site is licensed under the <a href="https://creativecommons.org/licenses/by/3.0/">
  Creative Commons Attribution 3.0 Unported License</a>`

How to add HTML on this yml file?

2018-04-27 02:50 UTC, mlinksva commented
@MatheusRV the string contains `:` so needed to be quoted. Done in b66c349

Thanks for starting on an implementation of this approach! 🙇 

There's one thing that I'm not enthusiastic about, and that is replicating license texts and metadata for each language. I think it's unavoidable given the Jekyll plugins available on GitHub Pages to have a file per license for each language, but maybe the metadata and texts could be moved so that the files in `_licenses` for each language would be nearly empty?

2018-04-27 18:14 UTC, mlinksva commented
Few other notes based on glancing again at opensource.guide and this PR:

- there are also individual pages (like `no-permission.md`) that probably would need to go in a new collection, like the `_articles` one in opensource.guide
- some portions of those pages, the super ugly code in `appendix.md` in particular, would need to be moved to includes so as not to be duplicated across translations
- it probably makes sense to have existing language not be in a `en-US` subdirectory to minimize redirects
- many of the tests will need to be modified based on final changed directory structure
- a script to start a translation would probably be useful, since it is going to involve creating a bunch of nearly empty files

2018-04-27 18:26 UTC, MatheusRV commented
I could translate to pt-BR

2018-04-27 18:37 UTC, mlinksva commented
@MatheusRV cool I'll definitely ping you about pt-BR for the first translation.

Just one other note, opensource.guide eventually implemented an even simpler approach in https://github.com/github/opensource.guide/pull/543 which we'd probably want to follow.

I'm probably going to open a new PR as a bunch of things need to change, but will keep this open until I do, and thank you very much again for getting it started (of course if you have the inclination, feel free to try a new PR taking into account all my rough notes above).

2018-04-27 18:44 UTC, matbrgz commented
Yes, thank you very much, I'm going to try to help as much as possible, I'm still learning about jekyll, but I'm enthusiastic myself, I'm writing my graduation monograph about this tecnology. I'm also trying to get into Github Campus Expert ..

You could be more didactic when it says of the changes so, I could not understand very well .. I'll try to sort with commits in that same PR.

2018-10-13 21:00 UTC, mlinksva commented
@MatheusRV thanks for continuing to work on this! I hope to get back to getting it into shape for shipping soon.

I see that you translated one license text (AFL-3.0) as a sketch. I hadn't planned for license text translations to be in scope, as some licenses have official or semi-official translations, and in general license tooling doesn't know how to deal with them -- a couple references on that in https://github.com/github/choosealicense.com/pull/527#issuecomment-348392371 -- I wouldn't suggest translating more license texts here as I'm not sure what we'd do with them at this point.

2018-10-13 21:26 UTC, matbrgz commented
I was really confused about the translation of the license. That would be a problem. We can keep the license in the original language until there is an official translation. I will reverse this change.

2019-01-12 14:01 UTC, wizardbyron commented
Is there anyone work on this ?

2019-01-15 16:31 UTC, MatheusRV commented
> Is there anyone working on this ?

Not yet, no time at this moment

2021-02-11 00:02 UTC, 1jionni approved these changes
@

>

2021-04-11 21:58 UTC, Andre601 commented
If this (or a different aproach) gets realized could I help with making a translation to german.

Just two things tho:

- How would it go about the license text? I believe it should stay in the original language (English) unless there's a official translation I suppose (if there is one would I need links to those then as I don't want to assume certain meanings).
- Is the grammar important here? I speak the Switzerland version of german which has some minor, yet important changes like no "ß" and probs a few other minor changes, so there could be conflicts with other people's version...

Other than that would I offer myself for the task once it's available to do. 👋

2021-04-11 22:55 UTC, mlinksva commented
@Andre601 license texts would not be translated. The main reason I haven't moved forward with this is some reorganization is required, likely separating the license texts from the metadata, some of which would be translated, and I just haven't made the time for it. I shall in the fullness of time.

As to how differences among varieties certain languages are handled, I'd guess however they are in other website translations. I don't recall seeing separate Swiss German translations on other sites, but happy to be wrong about that.

2021-04-12 23:26 UTC, MHRANN commented
> MatheusRV رشته حاوی `:`موارد مورد نیاز برای نقل قول است. در [b66c349](https://github.com/github/choosealicense.com/commit/b66c349c28db900decd7b1f9da3376c2a493fd42) انجام شده است[](https://github.com/github/choosealicense.com/commit/b66c349c28db900decd7b1f9da3376c2a493fd42)
> 
> برای شروع اجرای این رویکرد متشکریم! 🙇
> 
> یک چیز وجود دارد که من علاقه زیادی به آن ندارم ، و آن تکرار متن مجوز و فراداده برای هر زبان است. من فکر می کنم با توجه به افزونه های Jekyll موجود در GitHub Pages داشتن پرونده برای هر زبان برای هر مجوز اجتناب ناپذیر است ، اما آیا ممکن است متاداده ها و متون را منتقل کرد تا پرونده های موجود در `_licenses`هر زبان تقریبا خالی باشد؟

hi iam mhran I had a problem

2021-05-26 21:20 UTC, lastthyme approved these changes

2021-06-08 18:59 UTC, devkadirselcuk approved these changes

2021-06-08 19:27 UTC, Andre601 commented
> As to how differences among varieties certain languages are handled, I'd guess however they are in other website translations. I don't recall seeing separate Swiss German translations on other sites, but happy to be wrong about that.

(Man I completely forgot this here)

The sad truth is that the german from Germany is used most of the time, which is fine as reading the text isn't as bad as writing it.
It's just sad that most sides go with that version and don't bother looking into alternatives to make their sites a bit more personal if you get what I mean.

2021-07-06 19:03 UTC, ny030897 requested changes
_data/locale/pt-BR.yml

2021-07-06 19:20 UTC, ny030897 approved these changes
_licenses/pt-BR/afl-3.0.txt

2021-10-09 18:51 UTC, digidawww approved these changes

2022-05-04 22:19 UTC, azboyzranch approved these changes

2022-08-05 08:09 UTC, Moyhsb approved these changes

2022-11-12 16:53 UTC, Jiggnubs approved these changes

2022-11-22 19:32 UTC, DimaJah commented
# - [ ]

2023-04-15 12:36 UTC, Garrikk90 commented
> 
> `Your site is having problems building: There was a YAML syntax error on line 27 column 3 in _data/locale/en-US.yml: could not find expected ':' while scanning a simple key. For more information, see https://help.github.com/articles/page-build-failed-invalid-yaml-in-data-file/.`
> 
> `  licenses: The content of this site is licensed under the <a href="https://creativecommons.org/licenses/by/3.0/">
>   Creative Commons Attribution 3.0 Unported License</a>`
> 
> How to add HTML on this yml file?

2023-08-18 21:09 UTC, Nikis210 requested changes
[Texas.txt](direccion/termor/pula.arp)

2023-12-04 23:06 UTC, Tura187 approved these changes

2024-04-09 01:01 UTC, Dioliode approved these changes
DioX

2026-07-12 23:38 UTC, mlinksva commented
Superseded by #1344

2026-07-12 23:38 UTC, closed without merging